name = "QRCode"
uuid = "6cfbe66a-a49d-11e9-1842-750d329cfcbb"
authors = ["Jérémie Gillet <jie.gillet@gmail.com>"]
version = "0.1.0"

[deps]
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
